import json
import time
import re
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

# Initialize Geocoder
geolocator = Nominatim(user_agent="sri_lanka_grocery_tracker_v2")

def clean_address_for_search(address):
    """Removes 'No. XXX,' patterns which confuse the geocoder."""
    cleaned = re.sub(r"No\.?\s?\d+[A-Za-z/]?,\s?", "", address)
    return cleaned

def get_coordinates(address):
    try:
        # 1. Try Cleaned Address (Better success rate)
        search_query = f"{clean_address_for_search(address)}, Sri Lanka"
        location = geolocator.geocode(search_query, timeout=10)
        
        if location:
            return location.latitude, location.longitude
        
        # 2. Fallback → use town only
        town = address.split(",")[-1].strip()
        location = geolocator.geocode(f"{town}, Sri Lanka", timeout=10)
        
        if location:
            return location.latitude, location.longitude
        
        return None, None

    except GeocoderTimedOut:
        return get_coordinates(address)

# --- CONFIGURATION AREA ---
# 1. Change this to "Cargills" or "Keells"
CURRENT_CHAIN = "Cargills" 

# 2. Paste your list here
raw_store_list = [
    {"name": "FC STAPLES STREET", "address": "21, Staples Street, Colombo 02"},
    {"name": "FC KANDY", "address": "3, Dalada Veedia, Kandy"},
    {"name": "EX MOUNT LAVINIA", "address": "360, Galle Road, Mount Lavinia"},
    {"name": "FC WELLAWATTE", "address": "No:-256 3-B/1, Moor Road, Wellawatte, Colombo 06"},
    {"name": "FC MAJESTIC CITY", "address": "Majestic City, 10, Station Road, Colombo 04"},
    {"name": "FC MAHARAGAMA", "address": "75, Dehiwala Road, Maharagama"},
    {"name": "FC BANDARAWELA", "address": "7, Welimada Road, Bandarawella"},
    {"name": "FC NUWARA ELIYA", "address": "90, Kandy Road, Nuwaraeliya"},
    {"name": "FC NUGEGODA", "address": "240, High Level Road, Nugegoda"},
    {"name": "FC FORT", "address": "40, York Street, Fort, Colombo 01"},
    {"name": "FC MALABE", "address": "766, Kaduwela Road, Malabe"},
    {"name": "FC NEGOMBO", "address": "355, Main Street, Negombo"},
    {"name": "FC BORALESGAMUWA", "address": "231, Dehiwala Road, Boralasgamuwa"},
    {"name": "EX RAJAGIRIYA", "address": "349, Cotta Road, Rajagiriya"},
    {"name": "FC PITAKOTTE", "address": "407, Pitta Kotte Road, Pita Kotte"},
    {"name": "FC PANADURA", "address": "163, Galle Road, Panadura"},
    {"name": "FC KURUNEGALA", "address": "44, Negombo Road, Kurunegala"},
    {"name": "FC MATARA", "address": "60, Anagarika Dharmapala Mw, Matara"},
    {"name": "FC WATTALA", "address": "315, Negombo Road, Wattala"},
    {"name": "FC GAMPAHA", "address": "45, Bauddhaloka Mawatha, Gampaha"},
    {"name": "FC JAELA", "address": "49, Negombo Road, Ja-Ela"},
    {"name": "FC CHILAW", "address": "1, Jetty Street, Chilaw"},
    {"name": "FC PILIYANDALA", "address": "122/A, Kesbewa Road, Piliyandala"},
    {"name": "FC DEHIWALA", "address": "65 A, Galle Road, Dehiwala"},
    {"name": "FC RATNAPURA", "address": "Municipal Commercial Complex, Old Bus Stand Site, Nagarasaba Pedesa, Ratnapura"},
    {"name": "FC COLPETTY", "address": "407, Galle Road, Colpetty"},
    {"name": "EX THIMBIRIGASYAYA", "address": "90, Thimbirigasyaya Road, Colombo 05"},
    {"name": "FC NAWALA", "address": "264, Nawala Road, Nawala"},
    {"name": "EX MATARA", "address": "No. 1, Bus Stand Site, Matara"},
    {"name": "FC KADAWATHA", "address": "831, Kandy Road, Kadawatha"},
    {"name": "EX MALIGAWATTE", "address": "1141, Pradeepa Mawatha, Colombo 10"},
    {"name": "FC KEGALLE", "address": "447 / 2, Kandy Road, Kegalla"},
    {"name": "FC ALUTHGAMA", "address": "303, Main Street, Aluthgama"},
    {"name": "FC KOTAHENA", "address": "108, George R. de Silva Mw, Kotahena"},
    {"name": "FC AMBALANGODA", "address": "98 A, New Road, Ambalangoda"},
    {"name": "FC PARK ROAD", "address": "213, Park Road, Off Elvitigala Mw, Colombo 05"},
    {"name": "FC BERUWELA", "address": "162, Galle Road, Beruwela"},
    {"name": "FC KATUGASTOTA", "address": "271 A, Katugastota Road, Kandy"},
    {"name": "FC WARAKAPOLA", "address": "97, Kandy Road, Warakapola"},
    {"name": "EX ALEXANDRA PLACE", "address": "75, C.W.W. Kannangara Mw, Colombo 7"},
    {"name": "FC KARAGAMPITIYA", "address": "176, Hill Street, Karagampitiya, Dehiwala"},
    {"name": "FC MATALE", "address": "99 A, King Street, Mathale"},
    {"name": "FC PELIYAGODA", "address": "304, Negombo Road, Peliyagoda"},
    {"name": "EX HAVELOCK ROAD", "address": "323, Havelock Rd, Coombo 6"},
    {"name": "FC KELANIYA", "address": "878, Kandy Road, Kelaniya"},
    {"name": "FC AVISSAWELLA", "address": "91, Ratnapura Road, Avissawella"},
    {"name": "FC DEMATAGODA", "address": "297/7, Baseline Road, Dematagoda, Colombo 09"},
    {"name": "FC GALLE", "address": "24 & 26, Gamini Mawatha, Galle"},
    {"name": "FC HOMAGAMA", "address": "96, High Level Road, Homagama"},
    {"name": "FC KOHUWALA", "address": "89, S.D.S. Jayasinghe Mawatha, Kohuwala, Nugegoda"},
    {"name": "FC KOLONNAWA", "address": "Urban Council Premises, Kolonnawa, Wellampitiya"},

    {"name": "FC MOUNT LAVINIA STC", "address": "270, Galle Road, Mount Lavinia, S.T.C"},
    {"name": "FC EMBILIPITIYA", "address": "51, Nonagama Road, Embilipitiya"},
    {"name": "FC KOTTAWA", "address": "87, High Level Road, Kottawa"},
    {"name": "FC ANURADHAPURA", "address": "248, Main Street, Anuradhapura"},
    {"name": "FC WENNAPPUWA", "address": "25/2, Chilaw Road, Wennappuwa"},
    {"name": "FC MUTUWAL", "address": "54/1, Centre Road, Mattakkuliya"},
    {"name": "FC SEEDUWA", "address": "673, Negombo Road, Liyanagemulla, Seeduwa"},
    {"name": "EX BAMBALAPITIYA", "address": "762, Galle Rd, Colombo 4"},
    {"name": "FC BALANGODA", "address": "157, Old Road, Balangoda"},
    {"name": "FC KADUWELA", "address": "125 A, Colombo - Avissawella Rd, Kaduwela"},
    {"name": "FC MARADANA", "address": "585, Maradana Road, Maradana"},
    {"name": "FC BADULLA", "address": "18, Dharmadutha Road, Badulla"},
    {"name": "FC KANDANA", "address": "39 A, Negombo Road, Kandana"},
    {"name": "FC VAVUNIYA", "address": "137, Kandy Road, Vavuniya"},
    {"name": "EX PANADURA", "address": "205, Galle Road, Panadura"},
    {"name": "FC PILIMATALAWA", "address": "178, Colombo Road, Pilimathalawa"},
    {"name": "BC KATUBEDDA", "address": "241, Galle Road, Katubedda (Big City)"},
    {"name": "FC ATTIDIYA", "address": "251, Main Road, Attidiya"},
    {"name": "FC DAMBULLA", "address": "643, Anuradhapura Road, Dambulla"},
    {"name": "FC DICKWELLA", "address": "52, Mahawela Road, Dickwella"},
    {"name": "FC AKURANA", "address": "281, Matale Road, Akurana"},
    {"name": "FC HAMBANTOTA", "address": "Thissa Road, Hambantota"},
    {"name": "FC MINUWANGODA", "address": "40, Colombo Road, Minuwangoda"},
    {"name": "FC DELKANDA", "address": "352 B, Gamsaba Junction, Delkanda"},
    {"name": "FC KIRIBATHGODA", "address": "222, Kandy Road, Kiribathgoda"},
    {"name": "FC HATTON", "address": "171, Dimbulla Road, Hatton"},
    {"name": "EX KATUNAYAKE SLAF", "address": "SLAF Base Katunayaka"},
    {"name": "FC KATUKURUNDA", "address": "919, Galle Road, Katukurunda"},
    {"name": "FC KOSWATTE", "address": "290, Kaduwela Road, Koswatta"},
    {"name": "FC KOHUWALA 2", "address": "No.106/3, Dutugemunu Street, Kohuwala"},
    {"name": "FC MAHARAGAMA 2", "address": "No.147, High Level Road, Maharagama"},
    {"name": "FC MIRIHANA", "address": "No.108, Jubilee Post, Mirihana, Nugegoda"},
    {"name": "FC NUGEGODA 2", "address": "No.79, Stanley Thilakarathna Mawatha, Nugegoda"},
    {"name": "FC RATMALANA", "address": "No.143, Mount City, Galle Rd, Rathmalana"},
    {"name": "FC WIJERAMA", "address": "No.533, High Level Road, Wijerama, Nugegoda"},
    {"name": "FC KUNDASALE", "address": "Bamunupola Watta, Kundasale"},
    {"name": "FC PANADURA 2", "address": "No.518, Galle Rd, Panadura (02)"},
    {"name": "FC TANGALLE", "address": "No.4, Mahawela Rd, Tangalle"},
    {"name": "FC KOCHCHIKADE", "address": "No.37, Negombo Road, Kochchikade"},
    {"name": "FC PEPILIYANA", "address": "No.473/A, Colombo Road, Pepiliyana, Boralasgamuwa"},
    {"name": "FC KARAPITIYA", "address": "Namal Traders, Karapitiya"},
    {"name": "FC EHELIYAGODA", "address": "No.44, Main Street, Eheliyagoda"},
    {"name": "FC GAMPOLA", "address": "No.8/8, Nawalapitiya Road, Gampola"},
    {"name": "FC HORANA", "address": "No.142, Panadura Road, Horana"},
    {"name": "FC RAGAMA", "address": "No.33, Kadawatha Road, Ragama"},
    {"name": "FC NITTAMBUWA", "address": "No.89, Kandy Road, Nittambuwa"},
    {"name": "EX TRINCOMALEE", "address": "Linganagar Service Station (MPCS), Trincomalee"},
    {"name": "FC KALUTARA", "address": "No.272, Galle Road, Kalutara South"},
    {"name": "EX BIA KATUNAYAKE", "address": "CFC Departure Concord, B.I.A. Katunayake"},
    {"name": "FC KADAWATHA 2", "address": "No.317, Kandy Road, Kadawatha"},
    {"name": "FC KURUNEGALA 2", "address": "No.103, Dambulla Road, Kurunegala"},
    {"name": "FC MIRIGAMA", "address": "No.93, Giriulla Road, Mirigama"},
    {"name": "FC ATHURUGIRIYA", "address": "No.100, Main Road, Athurugiriya"},
    {"name": "FC MAWANELLA", "address": "No.22/C, Kandy Road, Mawanella"},

    {"name": "FC TRINCOMALEE", "address": "No.190, Thirugnanasampanthan Street, Trincomalee"},
    {"name": "FC KULIYAPITIYA", "address": "No.183, Hettipola Road, Kuliyapitiya"},
    {"name": "FC BANDARAGAMA", "address": "No.51, Panadura Road, Bandaragama"},
    {"name": "FC KALUTARA NORTH", "address": "No.264, Galle Road, Kalutara North"},
    {"name": "FC PANNALA", "address": "No.33, Kuliyapitiya Road, Pannala"},
    {"name": "FC WELIWERIYA", "address": "No.28, New Kandy Road, Weliweriya"},
    {"name": "FC DELGODA", "address": "No.348, New Kandy Road, Delgoda"},
    {"name": "FC BATTICALOA", "address": "No.67, St. Anthonys Street, Batticaloa"},
    {"name": "FC PANNIPITIYA", "address": "No.1499/A, Vidyala Junction, Hokandara Rd, Pannipitiya"},
    {"name": "FC BOKUNDARA", "address": "No.201/1A, Bokundara, Piliyandala"},
    {"name": "FC DHARGA TOWN", "address": "No.321/3, Main Street, Dhargatown"},
    {"name": "FC NAWALAPITIYA", "address": "No.51, Gampola Road, Nawalapitiya"},
    {"name": "FC AMPARA", "address": "Reegal Cinema, Nidahas Mawatha, Ampara"},
    {"name": "FC DICKMANS ROAD", "address": "No.15, Dickmans Road, Bambalapitiya"},
    {"name": "FC GRANDPASS", "address": "No.130/C, Layards Broadway, Grandpass, Colombo 14"},
    {"name": "FC KESBEWA", "address": "No.130A, Horana Road, Kesbewa"},
    {"name": "FC MALABE 2", "address": "No.162/7, Ratna Building, New Kandy Rd, Weliwita Junction, Malabe"},
    {"name": "FC MONERAGALA", "address": "No.105, Wellawaya Road, Monaragala"},
    {"name": "FC NEGOMBO 2", "address": "No.266, Colombo Road, Negombo"},
    {"name": "FC BATTARAMULLA", "address": "No.103, Athul Kotte Road, Battaramulla"},
    {"name": "FC WELISARA", "address": "No.768, Negombo Road, Welisara, Ragama"},
    {"name": "FC IPALOGAMA", "address": "Ranajayapura, Ipalogama"},
    {"name": "FC RAJAGIRIYA 2", "address": "No.395, Sri Jayawardanapura Mw, Welikada, Rajagiriya"},
    {"name": "FC KOTIKAWATTA", "address": "No.250, IDH Rd, Kotikawatta"},
    {"name": "FC PALMADULLA", "address": "No.115, Ratnapura Road, Pelmadulla"},
    {"name": "FC WADDUWA", "address": "No.527, Galle Road, Wadduwa"},
    {"name": "FC ETHULKOTTE", "address": "No.906, Kotte Road, Ethul Kotte, Kotte"},
    {"name": "FC JAELA 02", "address": "No.417, Negombo Road, Jaela"},
    {"name": "FC YAKKALA", "address": "No.99, Yakkala Park, Kandy Road, Yakkala"},
    {"name": "FC MAKOLA", "address": "No.99, Makola South, Makola"},
    {"name": "FC JAWATTA", "address": "No.60, Jawatta Road, Thimbirigasyaya"},
    {"name": "FC DUPLICATION", "address": "No.450 E, R A De Mel Mawatha, Colombo 03"},
    {"name": "FC MANIPPAY", "address": "No.120, Jaffna Road, Manipay"},
    {"name": "FC THIHARIYA", "address": "No.122/1, Parakumbamahal, Thihariya, Kalagedihena"},
    {"name": "EX ROYALPARK", "address": "No.115, Lake Drive, Rajagiriya"},
    {"name": "FC KANNATHTHIDI", "address": "No.54, Kannathiddy Road, Jaffna"},
    {"name": "FC KALAPALUWAWA", "address": "No.21/8, Buthgamuwa Road, Kalapaluwawa, Rajagiriya"},
    {"name": "FC BANDARAWATTE", "address": "No.160/9A, New Kandy Road, Bandarawatte, Biyagama"},
    {"name": "FC AKKARAIPATHTHU", "address": "No.143/B1, Kalmunai Road, Akkaraipattu"},
    {"name": "FC KALMUNEI", "address": "No.1034/1, Kalmunai 14"},
    {"name": "FC NORRIS CANAL", "address": "No.25, Norris Canal Road, Colombo 10"},
    {"name": "EX TRILLIUM RESIDENCE", "address": "No.153, Elvitigala Mawatha, Colombo 08"},
    {"name": "FC WARIYAPOLA", "address": "No.107, Kurunegala Road, Wariyapola"},
    {"name": "FC DANKOTUWA", "address": "No.35/37, Naththandiya Road, Dankotuwa"},
    {"name": "EX KURUWITA", "address": "No.96, Main Road, Kuruwita"},
    {"name": "EX RUWANWELLA", "address": "No.114, Main Street, Ruwanwella"},
    {"name": "EX DIGANA", "address": "Methsiripaya, New Town, Rajawella, Digana"},
    {"name": "FC KADURUWELLA", "address": "No.896, Batticaloa Road, Kaduruwela"},
    {"name": "FC KILINOCHCHI", "address": "No.7-10, Anthoneypillai Building, Karadibokku, Kilinochchi"},
    {"name": "EX SUWARAPOLA", "address": "No.428, Moratuwa Rd, Suwarapola, Piliyandala"},
    {"name": "EX HABARAKADA", "address": "No.575/14, Borella Road, Habarakada, Homagama"},
    {"name": "EX KOTIYAKUBURA", "address": "No.146, Ruwanwella Road, Kotiyakumbura"},
    {"name": "EX NEDIMALA", "address": "No.65 C, Pepiliyana Road, Nedimala, Dehiwala"},
    {"name": "FC MANCHANTHODUWAI", "address": "No.488, New Kalmunai Road, Manchanthoduwai"},

    {"name": "FC WELIMADA", "address": "No.11, Boralanda Road, Welimada"},
    {"name": "FC ELAKANDA", "address": "No.132, Canal Road, Elakanda"},
    {"name": "FC BATTICALOA 02", "address": "No.03, Gnanasooriyam Square, Trinco Road, Batticaloa"},
    {"name": "EX BENTOTA", "address": "No.118, Pahurumulla, Galle Road, Bentota"},
    {"name": "EX MORATUWELLA", "address": "No.487, New Galle Road, Moratuwella"},
    {"name": "FC GALEWELA", "address": "No.210, Kalawewa Junction, Galewela"},
    {"name": "FC PUTTALUM", "address": "No.97B, Kurunegala Road, Puttalam"},
    {"name": "FC POTHUVIL", "address": "Kaleej Front Building, Main Street, Pothuvil"},
    {"name": "FC WARD PLACE", "address": "No.48, Ward Place, Colombo 07"},
    {"name": "EX PASYALA", "address": "No.174 2/4, Kandy Road, Pasyala"},
    {"name": "FC ERAVUR", "address": "No.42/44, Main Street, Eravur"},
    {"name": "FC MARAWILA", "address": "No.65, Chilaw Road, Marawila"},
    {"name": "EX KANDANA", "address": "No.76, Station Road, Kandana"},
    {"name": "EX MELSIRIPURA", "address": "Cargills Food City Express, Dambulla Road, Melsiripura"},
    {"name": "EX POLGAHAWELA", "address": "No.23, Kurunegala Road, Polgahawela"},
    {"name": "EX KIRIDIWELLA", "address": "No.111, Radawana Road, Kirindiwela"},
    {"name": "EX NELLIYADI", "address": "No.163, Jaffna Road, Nelliyady"},
    {"name": "FC MATTEGODA", "address": "No.146/83, Salmal Pedesa, Mattegoda"},
    {"name": "FC THALAWATHUGODA", "address": "No.205/S, Pannipitiya Road, Thalawathugoda"},
    {"name": "FC SAMANTHURAI", "address": "No.32/2, Ampara Road, Viliniyady Junction, Sammanthurai"},
    {"name": "EX BELIATTA", "address": "No.52, Tangalle Road, Beliatta"},
    {"name": "FC THISSAMAHARAMA", "address": "No.142, Hambantota Road, Thissamaharama"},
    {"name": "EX MIDDENIYA", "address": "Liyanage Building, Weeraketiya Road, Middeniya"},
    {"name": "FC MORATUWA OLD RD", "address": "No.151, Main Street, Moratuwa"},
    {"name": "EX GALGAMUWA", "address": "No.37, Anuradhapura Road, Galgamuwa"},
    {"name": "EX MALWANA", "address": "No.52/10/A, Main Street, Malwana"},
    {"name": "FC CHUNNAKAM", "address": "No.91, K.K.S. Road, Chunnakam"},
    {"name": "EX MORATUMULLA", "address": "No.46, Main Street, Moratumulla"},
    {"name": "EX DEPANAMA", "address": "No.205, Borella Road, Depanama"},
    {"name": "EX MATALE ROSE ST", "address": "No.1/15, Rose Street, Matale"},
    {"name": "FC RATMALANA 02", "address": "No.417, Galle Road, Rathmalana"},
    {"name": "EX PUGODA", "address": "Cargills Food City, Hanwella Road, Kospitiyana, Pugoda"},
    {"name": "EX ALAWWA", "address": "No.151, Giriulla Road, Alawwa"},
    {"name": "EX BALAPITIYA", "address": "No.79, Galle Road, Balapitiya"},
    {"name": "EX SEEDUWA PALLIYAWATTA", "address": "No.344, Kotugoda Road, Palliya Junction, Raddolugama"},
    {"name": "EX SOUTHERN HIGHWAY A", "address": "Cargills Food City Express A, Canowin Arcade, Welipenna Rest Area"},
    {"name": "EX SOUTHERN HIGHWAY B", "address": "Cargills Food City Express B, Canowin Arcade, Welipenna Rest Area"},
    {"name": "FC HANWELLA", "address": "No.138/2B, Main Street, Hanwella"},
    {"name": "FC PALLEKELE", "address": "No.396, Digana Road, Pallekele"},
    {"name": "EX CTG PILIYANDALA", "address": "No.120, CT Gardens, Gangarama Road, Thumbowila, Piliyandala"},
    {"name": "FC AMBALANTHOTA", "address": "No.129, Jayantha Building, Tangalle Road, Ambalantota"},
    {"name": "FC GALLE 02", "address": "No.10/8, Wakwella Road, Galle"},
    {"name": "EX MAWARAMANDIYA", "address": "No.470, Delgoda Road, Mawaramandiya"},
    {"name": "FC DALUGAMA", "address": "No.334, Dalugama, Kelaniya"},
    {"name": "EX KARANDENIYA", "address": "No.343, Mahahendhanda, Karandeniya"},
    {"name": "FC KATUGASTOTA 2", "address": "No.452, Katugastota Road, Kandy"},
    {"name": "EX ERIYAGAMA", "address": "No.180, Colombo Road, Eriyagama"},
    {"name": "FC AMBALANGODA 2", "address": "No.37, New Road, Ambalangoda"},
    {"name": "EX PITIPANA", "address": "No.254/F, Avissawella Rd, Homagama"},
    {"name": "EX MULLERIYAWA", "address": "No.378, Avissawella Rd, Mulleriyawa, Angoda"},
    {"name": "EX SIDDAMULLA", "address": "No.77, Sangarama Road, Siddamulla, Piliyandala"},
    {"name": "EX DIVULAPITIYA", "address": "No.37, Bomugammana, Divulapitiya"},
    {"name": "EX DEANS ROAD", "address": "No.153, Deans Road, Colombo 10"},
    {"name": "EX BUTTALA", "address": "No.36, Monaragala Road, Buttala"},

    {"name": "EX MANIKHINNA", "address": "No.31, Kandy Road, Manikhinna"},
    {"name": "EX KATUNERIYA", "address": "St. Anthonies Building, Chilaw Road, Katuneriya"},
    {"name": "FC AKURESSA", "address": "No.83, Matara Road, Akuressa"},
    {"name": "FC GATAMBE", "address": "No.496, Gatambe, Peradeniya"},
    {"name": "FC STANLY TMW", "address": "No.143/5A, Stanly Thilakarathna Mawatha, Nugegoda"},
    {"name": "EX NALLURUWA", "address": "No.830, Galle Road, Nalluruwa"},
    {"name": "EX GINIGATHHENA", "address": "No.120/1, Nawalapitiya Road, Ginigathhena"},
    {"name": "FC PETHIYAGODA", "address": "No.16, Biyagama Road, Pethiyagoda, Kelaniya"},
    {"name": "EX ALUBOMULLA", "address": "No.256, Kurusa Handiya, Alubomulla, Panadura"},
    {"name": "EX BOPITIYA", "address": "No.1, Pamunugama Road, Bopitiya"},
    {"name": "EX AMPITIYA", "address": "No.63, Kandy Road, Ampitiya"},
    {"name": "EX RUKMALGAMA", "address": "No.33A, 107/108, Rukmalgama, Pannipitiya"},
    {"name": "EX PIRIVENA JUNCTION", "address": "No.567, Pirivena Junction, Maharagama Road, Boralasgamuwa"},
    {"name": "FC WELIGAMA", "address": "No.454, Old Galle Road, Weligama"},
    {"name": "EX HIKKADUWA", "address": "No.162, Galle Road, Hikkaduwa"},
    {"name": "EX DERANIYAGALA", "address": "No.58, Dehiowita Road, Deraniyagala"},
    {"name": "EX HABARADUWA", "address": "Dassana Building, Galle Road, Habaraduwa"},
    {"name": "EX HABARANA", "address": "No.72, Trincomalee Road, Habarana"},
    {"name": "EX WATTEGAMA", "address": "No.31, Matale Road, Wattegama"},
    {"name": "FC GANEMULLA", "address": "No.367, Kadawatha Road, Ganemulla"},
    {"name": "FC JAFFNA", "address": "No.420, Hospital Road, Jaffna"},
    {"name": "EX VEYANGODA", "address": "No.14, Good Shed Road, Veyangoda"},
    {"name": "FC EKALA", "address": "No.100, Sanasa Building, Minuwangoda Road, Ekala"},
    {"name": "FC COTA ROAD", "address": "No.260, N.M. Perera Mawatha, Cotta Road, Colombo 08"},
    {"name": "EX AMBEPUSSA", "address": "No.365, Colombo Road, Ambepussa"},
    {"name": "EX IBBAGAMUWA", "address": "No.5, Dambulla Road, Ibbagamuwa"},
    {"name": "EX POKUNUWITA", "address": "No.7, Colombo Road, Pokunuwita"},
    {"name": "FC KOTTAWA 02", "address": "No.867, High Level Road, Kottawa"},
    {"name": "FC MARINE DRIVE", "address": "No.27, 17th Lane, Marine Drive, Colombo 03"},
    {"name": "EX ARANGALA", "address": "No.462/2, Arangala Junction, Hokandara"},
    {"name": "FC WELLAWAYA", "address": "No.32, Hambantota Road, Wellawaya"},
    {"name": "EX GODAKAWELA", "address": "Main Street, Godakawela"},
    {"name": "EX DANDUGAMA", "address": "No.366, Colombo Road, Dandugama, Ja-Ela"},
    {"name": "FC KESELWATTE", "address": "No.29, Colombo Road, Keselwatta"},
    {"name": "EX MADAWACHCHIYA", "address": "No.102, Jaffna Road, Medawachchiya"},
    {"name": "EX GELIOYA", "address": "No.35/D, Peradeniya Road, Gelioya"},
    {"name": "FC HORANA 2", "address": "No.135, Anguruwathota Road, Horana"},
    {"name": "EX RAMBUKKANA", "address": "No.57, Mawanella Road, Rambukkana"},
    {"name": "EX DENIYAYA", "address": "No.04, Pallegama Road, Deniyaya"},
    {"name": "FC MATHUGAMA", "address": "No.93, Kalutara Road, Mathugama"},
    {"name": "EX KATUGODA", "address": "No.1/389, Matara Road, Katugoda, Galle"},
    {"name": "FC THALAHENA", "address": "No.723, Thalangama North, Thalahena"},
    {"name": "FC MARINE CITY", "address": "No.46, Station Road, Dehiwala"},
    {"name": "FC CHILAW 2", "address": "No.98, Colombo Road, Chilaw"},
    {"name": "EX KALUTARA CENTRAL", "address": "No.235, Central Junction, Nagoda, Kalutara South"},
    {"name": "FC MATALE 2", "address": "No.666, Trincomalee Street, Matale"},
    {"name": "EX GONAPOLA", "address": "No.105, Horana Road, Gonapola"},
    {"name": "EX GREEN ROAD", "address": "No.138/140, Greens Road, Negombo"},
    {"name": "EX NATTANDIYA", "address": "Kuliyapitiya Road, Naththandiya"},
    {"name": "EX PUWAKPITIYA", "address": "No.402/404/392/E, Colombo Road, Puwakpitiya, Avissawella"},
    {"name": "EX MADAMPE", "address": "No.33, Station Road, Madampe"},
    {"name": "EX GALAGEDARA", "address": "No.200/C, Hospital Junction, Galagedara"},
    {"name": "EX MULLAITTIVE", "address": "No.197, P.W.D. Road, Mullaittivu"},
    {"name": "EX HAVELOCK CITY", "address": "Club House Building, No.324, Havelock City, Wellawatta"},

    {"name": "FC PELAWATTA 02", "address": "No.470, Pannipitiya Road, Pelawatta"},
    {"name": "EX WATHUPITIWALA", "address": "No.392, Aththanagalla Road, Wathupitiwala"},
    {"name": "EX DELPE JUNCTION", "address": "No.295, Kadawatha Rd, Ragama"},
    {"name": "EX POOJAPITIYA", "address": "No.6/1/C, Owissa Road, Poojapitiya"},
    {"name": "EX HOKANDARA", "address": "No.404/1, Thalawathugoda Road, Hokandara South, Hokandara"},
    {"name": "EX ANAMADUWA", "address": "No.106, Puttalam Road, Anamaduwa"},
    {"name": "EX GODIGAMUWA", "address": "No.263, Piliyandala Road, Godigamuwa North, Maharagama"},
    {"name": "EX POLONNARUWA", "address": "No.13-A, Hospital Junction, Polonnaruwa"},
    {"name": "EX LEWIS PLACE NEGOMBO", "address": "No.132/A, Poruthota Road, Eththukala, Negombo"},
    {"name": "EX MAGGONA", "address": "No.396/5, Galle Road, Maggona"},
    {"name": "EX MARADAGAHAMULLA", "address": "No.89, Negombo Road, Maradagahamula"},
    {"name": "EX ASCON RESIDENCE", "address": "No.608-1/35, Dr. Danister de Silva Mawatha, Dematagoda"},
    {"name": "EX NEGOMBO Y JUNCTION", "address": "No.297/1, Meerigama Road, Mahahunupitiya, Negombo"},
    {"name": "EX ANDIAMBALAMA", "address": "No.223 D, Minuwangoda Road, Andiambalama"},
    {"name": "EX NELUWA", "address": "No.10, Sawijaya Building, Dellawa Road, Galle"},
    {"name": "FC NARAMMALA", "address": "No.161, Negombo Road, Narammala"},
    {"name": "EX AHANGAMA", "address": "No.55/A, Galle Road, Piyadigama, Ahangama"},
    {"name": "FC UDAHAMULLA", "address": "No.465 & 481, Old Kottawa Road, Udahamulla"},
    {"name": "EX WARAGODA", "address": "No.390, Waragoda Road, Kelaniya"},
    {"name": "EX RANMUTHUGALA", "address": "No.571/4, Ranmuthugala, Kadawatha"},
    {"name": "EX DALUPOTHA", "address": "No.594, Chilaw Road, Dalupotha, Negombo"},
    {"name": "EX RATMALANA STATION ROAD", "address": "No.24, Sri Gnanendra Road, Ratmalana"},
    {"name": "EX PANNIPITIYA OLD ROAD", "address": "No.257, Old Road, Moraketiya, Pannipitiya"},
    {"name": "EX HUNUPITIYA", "address": "No.58, Divulapitiya Road, Hunupitiya, Wattala"},
    {"name": "FC WERAHERA", "address": "No.202, Piliyandala Road, Werahera, Boralesgamuwa"},
    {"name": "EX PINNAWALA", "address": "Cargills Food City Express, No.563, Rambukkana Road, Pinnawala"},
    {"name": "EX MALKADUWAWA", "address": "Cargills Food City Express, Molawatta, Malkaduwawa, Kurunegala"},
    {"name": "EX MAKULUDUWA", "address": "No.16 B, Makuluduwa, Piliyandala"},
    {"name": "EX KATARAGAMA", "address": "No.53/1/1/2, Sella Road, Kataragama"},
    {"name": "EX KELANIYA", "address": "No.15, Vihara Mawatha, Cross Rd, Kelaniya"},
    {"name": "EX ELAPITIWALA", "address": "No.121, Elapitiwala, Ragama"},
    {"name": "EX MANNAR", "address": "Road 01, Pallimunai, Mannar"},
    {"name": "EX KALMUNAI", "address": "Cargills Food City, Saindhamaruthu, Kalmunai"},
    {"name": "EX KEKIRAWA", "address": "No.15, Malawa Village, Central Road, Kekirawa"},
    {"name": "FC PAGODA", "address": "No.41, Pagoda Road, Nugegoda"},
    {"name": "EX ICONIC RESIDENCE", "address": "Iconic Residence, No.110, Parliament Road, Rajagiriya"},
    {"name": "EX RAJAGIRIYA FAIRWAY", "address": "No.39, Perera Mawatha, Kotuwegoda"},
    {"name": "FC KAWDANA", "address": "No.10, Attidiya Road, Kawdana"},
    {"name": "EX RAHULA JUNCTION", "address": "No.39, Perera Mawatha, Buthgamuwa Road, Rajagiriya"},
    {"name": "EX MALIGAWATTE 2", "address": "No.1141, Pradeepa Mawatha, Maligawatte, Colombo 10"},
    {"name": "EX ALADENIYA", "address": "No.418/A, Kurunegala Road, Aladeniya, Werallagama, Kandy"},
    {"name": "EX KOTUGODA", "address": "No.80/H/7, Minuwangoda Road, Kotugoda"},
    {"name": "FC ENDERAMULLA", "address": "No.63/64, Dalupitiya Road, Enderamulla"},
    {"name": "FC GAMPAHA 2", "address": "No.257, Colombo Road, Gampaha"},
    {"name": "EX ON 320", "address": "No.320, Union Place, Colombo 2"},
    {"name": "EX MAGAMMANA", "address": "No.342/1, Kahathuduwa Road, Magammana, Homagama"},
    {"name": "FC MATARA 02", "address": "No.28/37, Araliya Mawatha, Kotuwegoda, Matara"},
    {"name": "FC WADDUWA 02", "address": "No.685, Galle Road, Wadduwa"},
    {"name": "FC ANURADHAPURA 02", "address": "No.46, Maithreepala Senanayake Mawatha, Anuradhapura"},
    {"name": "FC PILIYANDALA 02", "address": "No.134, Moratuwa Road, Piliyandala"},
    {"name": "FC HOMAGAMA 02", "address": "No.100, High Level Road, Homagama"},
    {"name": "FC KURUNEGALA 03", "address": "No.200, Colombo Road, Kurunegala"},
    {"name": "FC THALAPATHPITIYA", "address": "270/D, Thalapathpitiya Road, Thalapathpitiya"},

    {"name": "FC MORATUMULLA", "address": "No.411/1/2, De Zoisa Rd, Molpe, Moratuwa"},
{"name": "EX KALUBOWILA", "address": "No.2/A, Peris Rd, Kalubowila, Dehiwala"},
{"name": "FC SEEDUWA 02", "address": "No.245, Colombo Rd, Seeduwa"},
{"name": "EX PADUKKA", "address": "No.49/A, Hanwella Rd, Padukka"},
{"name": "FC MILLENNIUM CITY", "address": "No.383, Millennium City, Oruwala, Athurugiriya"},
{"name": "FC DAMBULLA 02", "address": "No.166, Kurunegala Rd, Dambulla"},
{"name": "FC WELLAMPITIYA", "address": "No.214, Colombo Road, Wellampitiya"},
{"name": "FC ARAWWALA", "address": "No.675/1, Arawwala, Pannipitiya"},
{"name": "FC KEGALLE 02", "address": "No.75/10, Hithinawatta Rd, Nidahas Mw, Kegalle"},
{"name": "EX DOMPE", "address": "No.217 J, Main Street, Dompe"},
{"name": "EX NAIWALA", "address": "Cargills Food City Express, Reality Plaza Building, Naiwala"},
{"name": "FC HOKANDARA", "address": "No.450, Pannipitiya Rd, Hokandara"},
{"name": "FC WIJERAMA 02", "address": "No.562, Gangodawila, Nugegoda"},
{"name": "FC KOLAMUNNA", "address": "No.78/E, Madapatha Rd, Kolomunna"},
{"name": "FC NITTAMBUWA 02", "address": "Unit 2, Veyangoda Rd, Nittambuwa"},
{"name": "FC MAHIYANGANAYA", "address": "No.113, Tile Factory Rd, Mahiyanganaya"},
{"name": "FC KATTIYA JUNCTION", "address": "No.30, Old Kesbewa Road, Gangodawila, Nugegoda"},
{"name": "FC GODAGAMA", "address": "No.179/1, Borella Road, Godagama"},
{"name": "FC KOSWATTE 02", "address": "No.07 & 7/3, Denzil Kobbekaduwa Mawatha, Koswatta"},
{"name": "FC GAMPAHA 03", "address": "No.27, Oruthota Road, Gampaha"},
{"name": "FC RATHNAPURA 02", "address": "No.111, Inner Circular Road, Rathnapura"},
{"name": "EX BINDUNUWEWA", "address": "Cargills Food City Express, Hill Side, Bindunuwewa"},
{"name": "EX KIRILLAWALA", "address": "No.538, Kandy Road, Kirillawala, Kadawatha"},
{"name": "FC HOMAGAMA 03", "address": "No.192, Athurugiriya Rd, Homagama"},
{"name": "FC KURANA", "address": "3701 M 1 L 1 677, Negombo Road, Kurana, Katunayake"},
{"name": "FC MIRISSA", "address": "Mahawaththa, Galle Road, Mirissa"},
{"name": "EX THALDUUWA", "address": "No.499/A, Thalduwa, Avissawella"},
{"name": "FC ALUTHGAMA 02", "address": "No.107/3, Galle Rd, Kaluwamodara, Aluthgama"},
{"name": "FC PILIMATHALAWA 02", "address": "No.231, Urapola, Pilimathalawa"},
{"name": "EX MARADANA 02", "address": "205 1/1, Maradana Road, Colombo 10"},
{"name": "EX INGIRIYA", "address": "No.50, Ratnapura Road, Ingiriya"},
{"name": "FC BANDARAGAMA 02", "address": "No.84, Panadura Road, Bandaragama"},
{"name": "FC KADAWATHA 03", "address": "No.467/11, Circular Road, Kadawatha"},
{"name": "FC KELANIYA 02", "address": "No.284, Old Kandy Road, Kelaniya"},
{"name": "FC BORUPANA", "address": "No.69/1, Borupana Road, Rathmalana"},
{"name": "FC PALLIMULLA", "address": "No.170, Old Galle Road, Pallimulla, Panadura"},
{"name": "FC RAWATHAWATTA", "address": "No.491, Galle Road, Rawathawatte, Moratuwa"},
{"name": "EX URAGASMANHANDIYA", "address": "No.5, L.S. Mawatha, Uragasmanhandiya"},
{"name": "EX NAWAGAMUWA", "address": "No.847, Avissawella Road, Nawagamuwa"},
{"name": "FC WELIPILLAWA", "address": "No.408/B/1, Welipillewa, Ganemulla"},
{"name": "FC BANDARAWELA 02", "address": "No.393, Badulla Rd, Bandarawela"},
{"name": "FC SARANANKARA ROAD", "address": "No.23, Sri Saranankara Rd, Kalubowila, Dehiwala"},
{"name": "FC WELISARA 02", "address": "No.607, Negombo Rd, Maththumagala"},
{"name": "FC RAGAMA 02", "address": "No.15, Peralanda Rd, Ragama"},
{"name": "FC ATHURUGIRIYA 02", "address": "No.91, Godagama Rd, Athurugiriya"},
{"name": "FC RAMBUKKANA", "address": "No.35, D.M. Dissanayake Kumarathunga Mawatha, Rambukkana"},
{"name": "EX DIYAGAMA NDT", "address": "Cargills Food City Express, Diyagama Institute of Technology, Diyagama"},
{"name": "EX URAPOLA", "address": "121/F, Ruwanwella Rd, Deenadamunuwa, Urapola"},
{"name": "FC KADUWELA 02", "address": "No.134, Colombo Rd, Kaduwela"},
{"name": "EX ELPITIYA", "address": "No.22 A, Pituwala Road, Elpitiya"},
{"name": "FC COLOMBO CITY CENTER", "address": "No.137, Sir James Pieris Mawatha, Colombo 02"},
]
# --------------------------

geocoded_data = []
print(f"🌍 Starting Geocoding for {CURRENT_CHAIN}... (1.5s delay)")

for store in raw_store_list:
    print(f"Processing: {store['name']}...")
    lat, lng = get_coordinates(store['address'])
    
    geocoded_data.append({
        "store_chain": CURRENT_CHAIN,
        "branch_name": store['name'],
        "latitude": lat,
        "longitude": lng,
        "address": store['address']
    })
    
    # Stay safe from being blocked (1.5s to 2s is safer)
    time.sleep(1.5)

# Save with a dynamic filename based on the chain name
filename = f'../data/geocoded/geocoded_{CURRENT_CHAIN.lower()}.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(geocoded_data, f, indent=4)

print(f"✅ Geocoding complete! Data saved to {filename}")